= The Prophet's (ﷺ) Prayer
Shaykh Muhammad Nasir-ud-deen al-Al-Albānī
v1.0, 2014-01-01
:toc:
:imagesdir: images
:homepage: http://asciidoctor.org

= Introduction

Praise be to Allaah, who made Prayer compulsory on his slaves and ordered them to establish it and perform it well; who linked success and felicity to humility in Prayer; who made it the criterion to distinguish between Eeman and Kufr ; and who made it a restrainer from shameful and unjust deeds.
Prayers and peace be upon our Prophet Muhammad, who was addressed in the Words of the Exalted:

"And We have sent down to you the Message, that you may explain clearly to the people what is sent for them"1, and who fully carried out this task. The Prayer was one of the most important things which he explained to the people, verbally and practically, even praying on the pulpit once - standing, bowing and prostrating, and then saying to them, I have done this so that you may follow me and learn my prayer.2 He obligated us to copy him in his prayer, saying, Pray as you have seen me praying.3 He also gave the good tidings to whoever prayed like him that such a person has a covenant with Allaah that He will enter him into the Garden, saying, There are five prayers which Allaah, Mighty and Sublime, has made compulsory: he who performs ablution well for them, prays them at their proper times, and is complete in their bowings, prostrations and humility, he has a guarantee from Allaah that He will forgive him; but he who does not do so, has no guarantee from Allaah: if He wishes, He will forgive him or if He wishes, He will punish him.4

Prayers and peace be also on his family and his pious and just Companions, who passed on to us his worship, prayer, sayings and actions (sallallaahu 'alaihi wa sallam), and who made these, and these alone, a Madhhab and a path for them to follow; and also on those who follow in their footsteps and tread their path until the Day of Judgment.

When I finished reading the book of prayer in At-Targheeb wat-Tarheeb by al-Haafiz al-Mundhiri (rahimahullaah) and teaching it to our brothers, four years ago, it became clear to us all the important position of the Prayer in Islaam; and the reward, grace and respect awaiting those who establish and perform it well; and that all this varies, depending on its closeness to the Prophet's prayer (sallallaahu 'alaihi wa sallam). This is what he indicated in his saying, Verily the slave prays a prayer of which nothing is written down for him except a tenth, ninth, eighth, seventh, sixth, fifth, quarter, third or half of it.5 Therefore, I reminded the brothers that it is not possible for us to perform prayer as it should be performed, or even approach that, unless we know the detailed description of the Prophet's prayer (sallallaahu 'alaihi wa sallam), including its essentials, manners, forms, supplications (du'aas) and remembrances (adhkaar), and then we make an effort to put that knowledge into practice carefully, for then we could hope that our prayers would restrain us from shameful and unjust deeds, and that the reward and blessings mentioned in the narrations would be written down for us.

However, detailed familiarity with all these aspects of prayer is unlikely to be achieved by most people nowadays, even many scholars, because of their limiting themselves to a particular Madhhab. But, as anyone concerned with assisting in compiling and studying the purified Sunnah knows, in every Madhhab there are sunnahs which are not found in other Madhhabs; moreover, in every Madhhab there are sayings and actions which cannot be authentically traced back to the Prophet (sallallaahu 'alaihi wa sallam) - most of these are found in the sayings of the later scholars6, many of whom we see firmly attributing these to the Prophet (sallallaahu 'alaihi wa sallam)!7 This is why the scholars of Hadeeth - may Allaah reward them well - have produced books of Takhreej on the famous books of the later scholars, explaining the rank of each hadeeth given in them: whether e.g. authentic, weak or fabricated. Examples of these books of Takhreej are: Al-'Inaayah fi Ma'rifah Ahaadeeth al- Hidaayah and At-Turuq wal-Wasaa'il fi Takhreej Ahaadeeth Khulaasah ad-Dalaa'il by Shaikh 'Abdul Qaadir ibn Muhammad al- Qurashi al-Hanafi; Nasb ar-Raayah li Ahaadeeth al-Hidaayah by Haafiz Zayla'i, and its abridged version ad-Dirayah by Haafiz Ibn Hajr al-Asqalaani, who also wrote Talkhees al-Habeer fi Takhreej Ahaadeeth ar-Raafi'i al-Kabir; there are many others, naming which will only lengthen this discussion.8 


My document provides...